### ISSUE TITLE
Visual Studio 2019 (Preview) Support

### ISSUE THREAD

**Issue by simplexidev** [mhoumann/CommentsPlus#8]
As the title describes; there are no other package provides this functionality in the VS Marketplace for VS2019.

**Comment by mhoumann** [comment]
Should be OK with version 1.8.1

**Comment by simplexidev** [comment]
I'm currently getting an error upon installation in Visual Studio 2019 Preview. It seems to be a `System.InvalidOperationException`, stating that it "Cannot find setup engine instance".

Here is a link to the raw [log file](https://pastebin.com/raw/nsjbRgDD) on pastebin,

And here in the error from the file above:

```
2/18/2019 2:10:42 PM - Beginning to install extension to Microsoft Visual Studio Community 2019...
2/18/2019 2:10:42 PM - Found setup instance bb59692a but not in launchable state.
2/18/2019 2:10:42 PM - Install Error : System.InvalidOperationException: Cannot find setup engine instance.
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineUtility.GetCurrentSetupInstance(IEngineHost engineHost)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.CreateEngine(IEngineHost engineHost, IServiceProvider serviceProvider, InstallFlags installFlags)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by mhoumann** [comment]
Weird. It has worked fine for me both on preview 2 and 4.
Is this installing from VS or just installing the vsix via Explorer?
You could try reporting it via the VS preview feedback button. The team is normally very quick to respond.

**Comment by simplexidev** [comment]
I reinstalled everything (Visual Studio-wise) and everything is working as intended. Minor crashes here and there, but that is on Microsoft 😉
